//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/!Files/!Coding/!CS/NomNoml/NomNoml/Grammar\Nomnoml.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="NomnomlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface INomnomlVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.classifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassifier([NotNull] NomnomlParser.ClassifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] NomnomlParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVisibility([NotNull] NomnomlParser.VisibilityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] NomnomlParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethod([NotNull] NomnomlParser.MethodContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] NomnomlParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClass([NotNull] NomnomlParser.ClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.association"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssociation([NotNull] NomnomlParser.AssociationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.dependency"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDependency([NotNull] NomnomlParser.DependencyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.generalization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneralization([NotNull] NomnomlParser.GeneralizationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.implementation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplementation([NotNull] NomnomlParser.ImplementationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.composition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComposition([NotNull] NomnomlParser.CompositionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.aggregation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregation([NotNull] NomnomlParser.AggregationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.note"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNote([NotNull] NomnomlParser.NoteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.hidden"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHidden([NotNull] NomnomlParser.HiddenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.classInteraction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassInteraction([NotNull] NomnomlParser.ClassInteractionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.interaction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteraction([NotNull] NomnomlParser.InteractionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="NomnomlParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] NomnomlParser.StartContext context);
}
