//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/!Files/!Coding/!CS/NomNoml/NomNoml/Grammar\Nomnoml.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="INomnomlListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class NomnomlBaseListener : INomnomlListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.classifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassifier([NotNull] NomnomlParser.ClassifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.classifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassifier([NotNull] NomnomlParser.ClassifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] NomnomlParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] NomnomlParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.visibility"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVisibility([NotNull] NomnomlParser.VisibilityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.visibility"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVisibility([NotNull] NomnomlParser.VisibilityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] NomnomlParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] NomnomlParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod([NotNull] NomnomlParser.MethodContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod([NotNull] NomnomlParser.MethodContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] NomnomlParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] NomnomlParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.class"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass([NotNull] NomnomlParser.ClassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.class"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass([NotNull] NomnomlParser.ClassContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.association"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssociation([NotNull] NomnomlParser.AssociationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.association"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssociation([NotNull] NomnomlParser.AssociationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.dependency"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDependency([NotNull] NomnomlParser.DependencyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.dependency"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDependency([NotNull] NomnomlParser.DependencyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.generalization"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneralization([NotNull] NomnomlParser.GeneralizationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.generalization"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneralization([NotNull] NomnomlParser.GeneralizationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.implementation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplementation([NotNull] NomnomlParser.ImplementationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.implementation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplementation([NotNull] NomnomlParser.ImplementationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.composition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComposition([NotNull] NomnomlParser.CompositionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.composition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComposition([NotNull] NomnomlParser.CompositionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.aggregation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggregation([NotNull] NomnomlParser.AggregationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.aggregation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggregation([NotNull] NomnomlParser.AggregationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.note"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNote([NotNull] NomnomlParser.NoteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.note"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNote([NotNull] NomnomlParser.NoteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.hidden"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHidden([NotNull] NomnomlParser.HiddenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.hidden"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHidden([NotNull] NomnomlParser.HiddenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.classInteraction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassInteraction([NotNull] NomnomlParser.ClassInteractionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.classInteraction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassInteraction([NotNull] NomnomlParser.ClassInteractionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.interaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteraction([NotNull] NomnomlParser.InteractionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.interaction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteraction([NotNull] NomnomlParser.InteractionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] NomnomlParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] NomnomlParser.StartContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
