//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/!Files/!Coding/!CS/NomNoml/NomNoml/Grammar\Nomnoml.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="NomnomlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface INomnomlListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.classifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassifier([NotNull] NomnomlParser.ClassifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.classifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassifier([NotNull] NomnomlParser.ClassifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] NomnomlParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] NomnomlParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVisibility([NotNull] NomnomlParser.VisibilityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVisibility([NotNull] NomnomlParser.VisibilityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] NomnomlParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] NomnomlParser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod([NotNull] NomnomlParser.MethodContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod([NotNull] NomnomlParser.MethodContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] NomnomlParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] NomnomlParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass([NotNull] NomnomlParser.ClassContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass([NotNull] NomnomlParser.ClassContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.association"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssociation([NotNull] NomnomlParser.AssociationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.association"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssociation([NotNull] NomnomlParser.AssociationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.dependency"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDependency([NotNull] NomnomlParser.DependencyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.dependency"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDependency([NotNull] NomnomlParser.DependencyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.generalization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneralization([NotNull] NomnomlParser.GeneralizationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.generalization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneralization([NotNull] NomnomlParser.GeneralizationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.implementation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplementation([NotNull] NomnomlParser.ImplementationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.implementation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplementation([NotNull] NomnomlParser.ImplementationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.composition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComposition([NotNull] NomnomlParser.CompositionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.composition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComposition([NotNull] NomnomlParser.CompositionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.aggregation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAggregation([NotNull] NomnomlParser.AggregationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.aggregation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAggregation([NotNull] NomnomlParser.AggregationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.note"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNote([NotNull] NomnomlParser.NoteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.note"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNote([NotNull] NomnomlParser.NoteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.hidden"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHidden([NotNull] NomnomlParser.HiddenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.hidden"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHidden([NotNull] NomnomlParser.HiddenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.classInteraction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassInteraction([NotNull] NomnomlParser.ClassInteractionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.classInteraction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassInteraction([NotNull] NomnomlParser.ClassInteractionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.interaction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteraction([NotNull] NomnomlParser.InteractionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.interaction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteraction([NotNull] NomnomlParser.InteractionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="NomnomlParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] NomnomlParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NomnomlParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] NomnomlParser.StartContext context);
}
